Community council update
OSGP/Documentation pull request #240
Opened 2020-11-27 15:04 UTC by Sander3003

Removed me from the community council / TAC

2020-11-27 15:05 UTC, Sander3003 commented
"Security issues can be reported on the one of the maintainers personally." is this correct?

2020-11-27 15:40 UTC, smvdheijden requested changes

2020-11-27 15:40 UTC, smvdheijden commented on Opensourcecommunity/Code-of-conduct.md
> +If you believe someone is violating the code of conduct, we ask that you report it by emailing the maillinlist gxf@lists.lfenergy.org.
maillinlist -> mailing list

2020-11-27 15:40 UTC, smvdheijden commented on Opensourcecommunity/Communication-and-contact.md
> +If you want to get in touch to discuss non-technical subjects, send us an email to the LF energy GXF maillinglist gxf@lists.lfenergy.org or open an [issue on Github](https://github.com/OSGP/documenta
maillinglist -> mailing list

2020-11-27 15:40 UTC, smvdheijden commented on Opensourcecommunity/Code-of-conduct.md
> +This code of conduct applies to all spaces managed by the GXF project (a LFenergy project). This includes IRC, the mailing lists, the issue tracker, DSF events, and any other forums created by the pr
LFenergy -> LF Energy

2020-11-27 15:40 UTC, smvdheijden commented on Opensourcecommunity/Communication-and-contact.md
> +Due to the sensible nature of security issues e.g. zero days, we prefer a responsible disclosure. Security issues can be reported on the one of the maintainers personally.
can be reported on the one of the maintainers personally -> can be reported at one of the maintainers personally

2020-11-27 15:40 UTC, smvdheijden commented on Opensourcecommunity/Governance.md
> +* [Robert Tusveld](https://github.com/Sander3003) - Architect - Chairman
Replace the github account (Sander3003) as well.

2020-11-30 16:41 UTC, Sander3003 commented on Opensourcecommunity/Code-of-conduct.md
> +If you believe someone is violating the code of conduct, we ask that you report it by emailing the maillinlist gxf@lists.lfenergy.org.
Thanks, fixed.

2020-12-01 09:55 UTC, smvdheijden requested changes

2020-12-01 09:55 UTC, smvdheijden commented on Opensourcecommunity/Code-of-conduct.md
> +If you believe someone is violating the code of conduct, we ask that you report it by emailing the mailling list gxf@lists.lfenergy.org.
mailing is written with a single "l"

2020-12-01 09:55 UTC, smvdheijden commented on Opensourcecommunity/Communication-and-contact.md
> +If you want to get in touch to discuss non-technical subjects, send us an email to the LF energy GXF mailling list gxf@lists.lfenergy.org or open an [issue on Github](https://github.com/OSGP/document
mailing

2020-12-01 14:42 UTC, Sander3003 commented
Bugs are fixed

2020-12-01 15:00 UTC, Jonasvdbo commented
@Sander3003 In regards to your question: "Security issues can be reported on the one of the maintainers personally. Is this correct? And is this the way to do it in the LF energy community?" There is no best practices in LF energy community for this yet. I would say security issues can be reported to gxf+owner@lists.lfenergy.org

2020-12-04 10:09 UTC, smvdheijden approved these changes

2020-12-04 13:57 UTC, merged