Update couplembusdevice.md
OSGP/Documentation pull request #285
Opened 2022-10-03 15:00 UTC by kroesctrl

Signed-off-by: Gerben Kroes <gerben@kroesctrl.nl>

2022-10-03 15:19 UTC, harrymiddelburgetall requested changes

2022-10-03 15:19 UTC, harrymiddelburgetall commented on domains/smartmetering/smartmeteringws/installation/couplembusdevice.md
> +If Force has value false, the check if Mbus device is connected to other device will be ignored
Isn't that just the other way around?

2022-10-03 18:02 UTC, kroesctrl commented on domains/smartmetering/smartmeteringws/installation/couplembusdevice.md
> +If Force has value false, the check if Mbus device is connected to other device will be ignored
klopt, heb het aangepast

2022-10-04 07:50 UTC, harrymiddelburgetall approved these changes

2022-10-05 12:24 UTC, merged